# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-FdrFet
version:      0.05
version_from: lib/Bio/FdrFet.pm
installdirs:  site
requires:
    Inline:                        0.45
    Inline::C:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
